main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: about
    name: About
    url: /about/
    weight: 2
  - identifier: language
    name: PT | EN
    params:
      type: language-switch
      label: true
    weight: 3
  - identifier: theme
    name: Theme
    params:
      type: theme-toggle
      label: false
    weight: 4

sidebar:
  - identifier: language
    name: Language
    weight: 100
